---
- name: Install apt-transport-https
  apt: name=apt-transport-https state=present

- name: Install ubuntu apt-key server
  environment:
    KEY: A2923DFF56EDA6E76E55E492D3A80E30382E94DE
  shell: >
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$KEY" ||
    gpg --keyserver pgp.mit.edu --recv-keys "$KEY" ||
    gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$KEY" ||
    gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "$KEY" ||
    gpg --keyserver keyserver.pgp.com --recv-keys "$KEY"
  args:
    executable: /bin/bash
  when: datadog_apt_key_url_new is not defined
  retries: 10
  delay: 6
  register: result
  until: result is succeeded

- name: Install Datadog apt-key
  apt_key: id=A2923DFF56EDA6E76E55E492D3A80E30382E94DE url={{ datadog_apt_key_url_new }} state=present
  when: datadog_apt_key_url_new is defined
  retries: 10
  delay: 6
  register: result
  until: result is succeeded

- name: Ensure Datadog non-https repositories are deprecated
  apt_repository:
    repo: "{{ item }}"
    state: "absent"
    update_cache: yes
  with_items:
    - "deb http://apt.datadoghq.com/ stable main"
    - "deb http://apt.datadoghq.com/ stable 6"

- name: Ensure Datadog repository is up-to-date
  apt_repository:
    repo: "{{ datadog_apt_repo }}"
    state: "{% if datadog_agent5 %}absent{% else %}present{% endif %}"
    update_cache: yes

- name: Ensure Datadog repository is up-to-date (agent5)
  apt_repository:
    repo: "{{ datadog_agent5_apt_repo }}"
    state: "{% if datadog_agent5 %}present{% else %}absent{% endif %}"
    update_cache: yes

- name: Ensure pinned version of Datadog agent is installed
  apt:
    name: datadog-agent={{ datadog_agent_version }}
    state: present
    force: "{{ datadog_agent_allow_downgrade }}"
    update_cache: yes
    cache_valid_time: "{{ datadog_apt_cache_valid_time }}"
  when: datadog_agent_version != ""

- name: Ensure Datadog agent is installed
  apt:
    name: datadog-agent
    state: latest
    update_cache: yes
    cache_valid_time: "{{ datadog_apt_cache_valid_time }}"
  when: datadog_agent_version == ""
